CanteenASP/CanteenASP/Controllers/Components/MealsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Model;
using System.Globalization;

namespace CanteenASP.Controllers.Components
{
    public class MealsViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(Order listOrder)
        {
            CultureInfo cul = CultureInfo.GetCultureInfo("vi-VN");
            if(listOrder != null)
            {
                listOrder.TotalPrice = double.Parse(listOrder.TotalPrice).ToString("#,###", cul.NumberFormat);

            }
            return View("Default", listOrder);
        }
    }
}

CanteenASP/CanteenASP/Controllers/HomeController.cs
using API;
using API.Helper;
using CanteenASP.Models;
using Microsoft.AspNetCore.Mvc;
using Model;
using MongoDB.Bson;
using System.Diagnostics;
using System.Globalization;


namespace CanteenASP.Controllers
{
    public class HomeController : BaseController
    {
        private readonly ILogger<HomeController> _logger;
        private readonly FoodService _foodService;
        private readonly UserService _userService;
        private readonly OrderService _orderService;

        public HomeController(ILogger<HomeController> logger, IWebHostEnvironment webHostEnvironment)
        {
            _logger = logger;
            _foodService = new FoodService();
            _userService = new UserService();
            _orderService = new OrderService();
        }

        public async Task<IActionResult> Index()
        {
            var foods = await _foodService.GetAll();
            
            CultureInfo cul = CultureInfo.GetCultureInfo("vi-VN");
            var userId = HttpContext.Session.GetString("UserId");
            if (userId != null)
            {
                var orders = await _orderService.GetOrdersByUser(userId);
                ViewBag.Orders = orders.Where(x => x.OrderTime.Date == DateTime.Now.Date).FirstOrDefault();
            }
            foreach (var item in foods)
            {
                item.Price = double.Parse(item.Price).ToString("#,###", cul.NumberFormat);
            }
            ViewData["Message"] = TempData["Message"];
            ViewData["Flag"] = TempData["Flag"];  
            return View(foods);
        }

        public async Task<IActionResult> Meals(int meal)
        {
            var foods = await _foodService.GetFoodByMealTime((MealTime)meal);
            foods = foods.Where(x => x.Type == (Model.Type)2).ToList();
            CultureInfo cul = CultureInfo.GetCultureInfo("vi-VN");
            foreach (var item in foods)
            {
                item.Price = double.Parse(item.Price).ToString("#,###", cul.NumberFormat);
            }
            if(meal == 1)
            {
                ViewBag.Meal = "Breakfast";
            }
            else if(meal == 2)
            {
                ViewBag.Meal = "Lunch";
            }
            else
            {
                ViewBag.Meal = "Dinner";
            }    
            return View(foods);
        }

        public async Task<IActionResult> Details(string id)
        {
            var food = await _foodService.GetItem(id);
            CultureInfo cul = CultureInfo.GetCultureInfo("vi-VN");
            food.Price = double.Parse(food.Price).ToString("#,###", cul.NumberFormat);
            return View(food);
        }

        public async Task<IActionResult> OptionDetails(int meal)
        {
            var foods = await _foodService.GetFoodByMealTime((MealTime)meal);
            foods = foods.Where(x => x.Type == (Model.Type)1).ToList();
            var details = new List<string>();
            foreach(var item in foods)
            {
                details.Add(item.Detail);
            }
            ViewData["details"] = details;
            return View(foods);
        }
        [HttpPost]
        public async Task<IActionResult> Order([FromBody] OrderPayload orderPayload)
        {
            var userId = HttpContext.Session.GetString("UserId");
            if (userId == null)
            {
                return Json(new { redirectToUrl = Url.Action("Index", "User") });
            }
            var user = await _userService.GetItem(userId);
            var food = await _foodService.GetItem(orderPayload.Id);
            food.Size = (Size)int.Parse(orderPayload.Size);
            var orderTime = DateTime.Now;
            var flag = await _orderService.MealTimeIsExist(userId, food.MealTime);
            
            if (!flag)
            {
                var order = new Order()
                {
                    User = user,
                    Food = food,
                    OrderTime = orderTime,
                    TotalPrice = (float.Parse(food.Price) + ((float)food.Size - 1) * 5000).ToString()
                };
                var res = await _orderService.Create(order);
                if (!res)
                    TempData["Message"] = "Time to order this meal is up!";
            }
            else
                TempData["Message"] = "This meal has already ordered today!";

            return Json(new { redirectToUrl = Url.Action("Index", "Home") });
        }

        [HttpPost]
        public async Task<IActionResult> OptionOrder([FromBody] List<OrderPayload> orderPayloads)
        {
            var userId = HttpContext.Session.GetString("UserId");
            if (userId == null)
            {
                return Json(new { redirectToUrl = Url.Action("Index", "User") });
            }
            var user = await _userService.GetItem(userId);
            var orderTime = DateTime.Now;
            var rice = new Food
            {
                Id = new ObjectId().ToString(),
                Description = "Cơm trắng bắc hương",
                Detail = "100% tinh bột",
                Name = "Cơm",
                Price = "10000",
                Type = Model.Type.Option,
            };
            List<Food> foods = new List<Food>();
            var totalPrice = 0;
            
            foreach(var item in orderPayloads)
            {
                var food = await _foodService.GetItem(item.Id);
                food.Size = (Size)int.Parse(item.Size);
                var price = int.Parse(food.Price) + ((int)food.Size - 1) * 5000;
                totalPrice += price;
                foods.Add(food);
            }
            rice.MealTime = foods[0].MealTime;
            var flag = await _orderService.MealTimeIsExist(userId, foods);
            if (!flag)
            {
                var order = new Order()
                {
                    User = user,
                    Food = rice,
                    Foods = foods,
                    OrderTime = orderTime,
                    TotalPrice = (totalPrice + int.Parse(rice.Price)).ToString()
                };
                var res = await _orderService.Create(order);
                if (!res)
                    TempData["Message"] = "Time to order this meal is up!";
            }   
            else
                TempData["Message"] = "This meal has already ordered today!";
            return Json(new { redirectToUrl = Url.Action("Index", "Home") });
        }

        public async Task<IActionResult> CancelOrder(string id)
        {
            var res = await _orderService.Delete(id);
            if (res)
            {
                TempData["Message"] = "Canceled order successfully!";
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CanteenASP/CanteenASP/Views/Home/Details.cshtml
@{
    ViewData["Title"] = "Details food";
    var price = @Model.Price;
    var id = @Model.Id;
}

@model Model.Food
<style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    body {
        background-color: whitesmoke !important;
    }

    .img img {
        width: 100%;
        /* height: 100%; */
    }

    .img {
        /*width: 300px;*/
    }

    .info button {
        width: 100%;
        height: 40px;
        border-radius: 20px;
    }

    .info {
        padding-left: 60px;
    }

        .info p {
            margin: 30px 0;
        }

    .card-view {
        padding: 40px;
        background-color: #fff;
        border-radius: 20px;
    }
</style>


<div class="container" style="margin-top: 100px;">
    <div class="card-view">
        <div class="row" style="padding: 0 10%;">
            <div>
                <div class="row">
                    <div class="col-md-8 img">
                        <img src="/assets/@Model.Image">
                    </div>
                    <div class="col-md-4 info">
                        <h3>@Model.Name</h3>
                        <p id="price" name="price" style="color: red;">@Model.Price VNĐ</p>
                        <!--Pick size-->
                        <h6>Pick size</h6>
                        <input type="radio" class="btn-check" name="size" id="option1" onclick="handleCheck(this)" autocomplete="off" value="1" checked>
                        <label class="btn btn-primary" for="option1">Small</label>

                        <input type="radio" class="btn-check" name="size" id="option2" onclick="handleCheck(this)" value="2" autocomplete="off">
                        <label class="btn btn-primary" for="option2">Medium</label>

                        <input type="radio" class="btn-check" name="size" id="option3" onclick="handleCheck(this)" value="3" autocomplete="off">
                        <label class="btn btn-primary" for="option3">Large</label>
                        <!--End pick size-->
                        <p style="padding: 0 25px;"><a class="order-button" style="text-decoration:none!important;" onclick="sendOrder()">Order</a></p>
                        <h5>Details</h5>
                        <p>@Model.Detail</p>
                    </div>
                </div>
                <div class="row">
                    <h5>Descriptions</h5>
                    <p>@Model.Description</p>
                    <h6>Side dishes</h6>
                    <p>@Model.SideDishes</p>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
<script>

    var si = '1';

    function handleCheck(size){
        let priceText = document.getElementById("price");
        let p = @price * 1000 + (parseInt(size.value) - 1) * 5000;
        let pr = p / 1000;
        priceText.innerHTML = pr + '.000' + ' VNĐ';
        si = size.value;
    };

   function sendOrder(){
        var data = JSON.stringify({
        'id' : '@id',
        'size' : si
    });

    $.ajax({
        url: '/Home/Order',
        type: 'POST',
        async: true,
        data: data,
        success: function(response){
            console.log(response.redirectToUrl);
            window.location.href = response.redirectToUrl;
        },
        contentType: 'application/json'
    });
   }

</script>
}

CanteenASP/CanteenASP/Views/Home/Index.cshtml
@using Model
@{
    ViewData["Title"] = "Trang chủ";
    var listOrder = ViewBag.Orders;
    var flag = ViewData["Flag"];
}

@model List<Model.Food>


<div class="container-fluid banner">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="/assets/—Pngtree—board food lunch food_917623.jpg" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="/assets/—Pngtree—bread ketchup butter flour chopping_1103257.jpg" alt="Second slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="/assets/—Pngtree—board food lunch food_917623.jpg" alt="Third slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

<div class="container">






    @if (ViewData["Message"] != null)
    {
        @*<div id="msgAlert" class="alert alert-danger" role="alert">
            @ViewData["Message"]
            </div>*@
        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="false">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Notification</h5>

                    </div>
                    <div class="modal-body">
                        @ViewData["Message"]
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" id="closeModal" onclick="closeModal()" data-dismiss="modal">Close</button>

                    </div>
                </div>
            </div>
        </div>
    }

    @await Component.InvokeAsync("Meals", listOrder)



</div>

@section Scripts{
<script>


    //
    setTimeout(function () {
            $("#msgAlert").fadeOut('slow');
        }, 2000);
     //
     document.addEventListener('DOMContentLoaded', ready);
     function ready(){
        var option = document.getElementById("option-meal");
        option.addEventListener('click', openDetail);
        }
        

    

        function openDetail(){
            var detail = document.getElementById("detail");
            detail.style.display = "block";
        }
        function closeDetail(){
            var detail = document.getElementById("detail");
            detail.style.display = "none";
        }


     var modal = document.getElementById('myModal');
     modal.style.display = "unset";
     modal.style.opacity = "unset";

     function closeModal(){
         modal.style.zIndex = "unset";
         modal.style.display = "none";
         modal.style.opacity = "0";
     }
</script>
}

CanteenASP/CanteenASP/Views/Home/Meals.cshtml
@using Model
@{
    ViewData["Title"] = "Trang chủ";
    var listOrder = (List<Order>)ViewBag.Orders;
    var flag = ViewData["Flag"];
    //var size = 1;
    //var id = "";
}

@model List<Model.Food>


<div class="container-fluid banner">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="/assets/—Pngtree—board food lunch food_917623.jpg" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="/assets/—Pngtree—bread ketchup butter flour chopping_1103257.jpg" alt="Second slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="/assets/—Pngtree—board food lunch food_917623.jpg" alt="Third slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

<div class="container">

    @*<div id="msgAlert" class="alert alert-danger" role="alert">
        @ViewData["Message"]
        </div>*@
    <!-- Modal -->
    <div class="modal fade" id="sizeModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="false">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Notification</h5>

                </div>
                <div class="modal-body">
                    <h6>Pick size</h6>
                    <input type="radio" class="btn-check" name="size" id="option1" autocomplete="off" value="1" checked>
                    <label class="btn btn-primary" for="option1">Small</label>

                    <input type="radio" class="btn-check" name="size" id="option2" value="2" autocomplete="off">
                    <label class="btn btn-primary" for="option2">Medium</label>

                    <input type="radio" class="btn-check" name="size" id="option3" value="3" autocomplete="off">
                    <label class="btn btn-primary" for="option3">Large</label>

                </div>
                <div class="modal-footer">
                    <a class="btn btn-success" asp-controller="Home" asp-action="Order" onclick="sendData()">Order</a>
                    <button type="button" class="btn btn-secondary" id="closeModal" onclick="closeModal()" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>






    <!--Template List combo-->
    @*<h2>@ViewBag.Meal</h2>*@
    <div class="carousel-container">
        <!--Option-->
        <div class="row">
            <div class="col-md-4 col-sm-4" style="padding:0 50px; margin: 15px 0;">
                <div class="card">
                    <div class="img"><a asp-action="OptionDetails" asp-route-meal="@Model[0].MealTime"><img src="/assets/comtuchon.jpg"></a></div>
                    <div class="info">
                        <h4><a asp-action="OptionDetails" asp-route-meal="@((int)Model[0].MealTime)">Custom meal</a></h4>
                        <h6>Món phụ: </h6>
                        <div>
                            <span style="color: red;">VNĐ</span>
                        </div>
                    </div>
                    <p>
                        <a class="order-button" asp-action="OptionDetails" asp-route-meal="@((int)Model[0].MealTime)">Order</a>
                    </p>
                </div>
            </div>
            @foreach (var item in Model)
            {
                <div class="col-md-4 col-sm-4" style="padding:0 50px; margin: 15px 0;">
                    <div class="card">
                        <div class="img"><a asp-action="Details" asp-route-id="@item.Id"><img src="/assets/@item.Image"></a></div>
                        <div class="info">
                            <h4><a asp-action="Details" asp-route-id="@item.Id">@item.Name</a></h4>
                            <h6>Món phụ: @item.SideDishes</h6>
                            <div>
                                <span style="color: red;">@item.Price VNĐ</span>
                            </div>
                            <input type="text" value="@item.Id" id="@item.Id" style="display:none;" />
                        </div>
                        <p>
                            <a asp-action="Details" asp-route-id="@item.Id" class="order-button">Order</a>
                        </p>
                    </div>
                </div>

            }
        </div>
    </div>


</div>

@section Scripts{
<script>

    const prev  = document.querySelector('.prev');
    const next = document.querySelector('.next');
    //

    //
    const track = document.querySelector('.track');


    let carouselWidth = document.getElementById('combo_carousel').offsetWidth;

    window.addEventListener('resize', () => {
      carouselWidth = document.getElementById('combo_carousel').offsetWidth;
    })
    //track
    let index = 0;

    next.addEventListener('click', () => {
      index++;
      prev.classList.add('show');
      track.style.transform = `translateX(-${index * carouselWidth}px)`;

      if (track.offsetWidth - (index * carouselWidth) < carouselWidth) {
        next.classList.add('hide');
      }
    });

    prev.addEventListener('click', () => {
      index--;
      next.classList.remove('hide');
      if (index === 0) {
        prev.classList.remove('show');
      }
      track.style.transform = `translateX(-${index * carouselWidth}px)`;
    });
    //

    setTimeout(function () {
            $("#msgAlert").fadeOut('slow');
        }, 2000);
     //

     var modal = document.getElementById('sizeModal');
     modal.style.display = "none";
     modal.style.opacity = "unset";

     function closeModal(){
         var modal = document.getElementById('sizeModal');
         modal.style.zIndex = "unset";
         modal.style.display = "none";
         modal.style.opacity = "0";
     }
     function openModal(){
         var modal = document.getElementById('sizeModal');
         modal.style.display = "block";
         modal.style.opacity = "100";
         modal.style.zIndex = "1055";

     }
     function sendData(){

     }
</script>
}