CanteenASP/CanteenASP/Areas/Admin/Controllers/FoodController.cs
using API;
using API.Interface;
using CanteenASP.Controllers;
using Microsoft.AspNetCore.Mvc;
using Model;
using MongoDB.Bson;

namespace CanteenASP.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class FoodController : AdminBaseController
    {
        readonly FoodService _foodService;
        string _pWwwRoot;

        public FoodController(IHostEnvironment webHostEnviroment)
        {
            this._foodService = new FoodService();
            _pWwwRoot = Path.Combine(webHostEnviroment.ContentRootPath, "wwwroot");
        }

        public async Task<IActionResult> Index()
        {
            var lFood = await _foodService.GetAll();
            return View(lFood);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Create(Food food, List<IFormFile> postedFiles)
        {
            if(string.IsNullOrEmpty(food.Name) 
                || string.IsNullOrEmpty(food.Price)
                || string.IsNullOrEmpty(food.Detail))
                return View(food);

            string path = Path.Combine(_pWwwRoot, "assets");
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }

            if (postedFiles.Count != 0)
            {
                var filename = DateTime.Now.ToString("HHmmss_ddMMyyyy") + ".png";
                food.Image = filename;
                using (FileStream stream = new FileStream(Path.Combine(path, filename), FileMode.Create))
                {
                    postedFiles[0].CopyTo(stream);
                }
            }

            var result = await _foodService.Create(food);
            if(result)
            {
                return RedirectToAction("Index");
            }
            return View(food);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var food = await _foodService.GetItem(id);
            return View(food);
        }

        [HttpPost]
        [Obsolete]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Edit(Food food, List<IFormFile> postedFiles)
        {
            if (string.IsNullOrEmpty(food.Name)
                || string.IsNullOrEmpty(food.Price))
                return View(food);

            string path = Path.Combine(_pWwwRoot, "assets");
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }

            if (postedFiles.Count != 0)
            {
                if(!string.IsNullOrEmpty(food.Image))
                {
                    System.IO.File.Delete(Path.Combine(path, food.Image));
                }

                var filename = DateTime.Now.ToString("HHmmss_ddMMyyyy") + ".png";
                food.Image = filename;
                using (FileStream stream = new FileStream(Path.Combine(path, filename), FileMode.Create))
                {
                    postedFiles[0].CopyTo(stream);
                }
            }

            var result = await _foodService.Update(food);
            if (result)
            {
                return RedirectToAction("Index");
            }
            return View(food);
        }

        public async Task<IActionResult> Delete(string id)
        {
            await _foodService.Delete(id);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "User", new { area = "" });
        }
    }
}

CanteenASP/CanteenASP/Areas/Admin/Controllers/OrderController.cs
using API;
using CanteenASP.Controllers;
using Microsoft.AspNetCore.Mvc;
using Model;
using System.Text;

namespace CanteenASP.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class OrderController : BaseController
    {
        readonly OrderService _orderService;
        string _pWwwRoot;
        static List<Order> _tmpOrders = new List<Order>();

        public OrderController(IHostEnvironment webHostEnviroment)
        {
            this._orderService = new OrderService();
            _pWwwRoot = Path.Combine(webHostEnviroment.ContentRootPath, "wwwroot");
        }

        public async Task<IActionResult> Index(string nameFood, string mealTime, string startTime, string endTime)
        {
            var lOrder = await _orderService.GetAll();
            if (!string.IsNullOrEmpty(mealTime) && mealTime != "--Select meal time--")
                lOrder = lOrder.Where(x => x.Food.MealTime.ToString() == mealTime).ToList();

            if (!string.IsNullOrEmpty(nameFood))
            {
                lOrder = lOrder.Where(x => x.Food.Name.ToLower().Contains(nameFood.ToLower())).ToList();
            }

            if (!string.IsNullOrEmpty(startTime))
            {
                var start = DateTime.ParseExact(startTime, "yyyy-MM-dd", System.Globalization.CultureInfo.InvariantCulture);
                lOrder = lOrder.Where(x => x.OrderTime >= start).ToList();
            }

            if (!string.IsNullOrEmpty(endTime))
            {
                var end = DateTime.ParseExact(endTime, "yyyy-MM-dd", System.Globalization.CultureInfo.InvariantCulture);
                lOrder = lOrder.Where(x => x.OrderTime <= end).ToList();
            }

            _tmpOrders?.Clear();
            _tmpOrders?.AddRange(lOrder);

            ViewData["MealTime"] = mealTime;
            ViewBag.StartTime = startTime; // "2021-12-21"
            ViewBag.EndTime = endTime;
            ViewBag.Name = nameFood;

            return View(lOrder);
        }

        
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Export()
        {
            var result = await _orderService.ExportCsvWithList(_tmpOrders);
            var path = Path.Combine(this._pWwwRoot, "export");
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }

            var filename = DateTime.Now.ToString("Export_HHmmss_ddMMyyyy") + ".csv";
            System.IO.File.WriteAllText(Path.Combine(path, filename), result, Encoding.UTF8);  

            return RedirectToAction("Index");
        }
    }
}

CanteenASP/CanteenASP/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CanteenASP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CanteenASP.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" >Canteen</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Food" asp-action="Index">Food</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="User" asp-action="Index">User</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Order" asp-action="Index">Order</a>
                        </li>
                    </ul>
                </div>
                <!-- Navbar-->
                <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                    <li><a class="nav-link text-dark" asp-action="Logout" asp-controller="Food">Logout</a></li>
                </ul>
            </div>
        </nav>

        
    </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>