CanteenASP/CanteenASP/Areas/Admin/Controllers/UserController.cs
using API;
using CanteenASP.Controllers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Model;

namespace CanteenASP.Areas.Admin.Controllers
{
    [Area("Admin")]
    
    public class UserController : BaseController
    {
        readonly UserService _userService;

        public UserController()
        {
            this._userService = new UserService();
        }

        public async Task<IActionResult> Index()
        {
            var lUser = await _userService.GetAll();
            return View(lUser);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(User user)
        {
            user.DisplayName = user.FirstName + " " + user.LastName;
            user.Password = Common.MD5Hash(input: user.Password);

            var result = await _userService.Create(user);
            if (result)
            {
                return RedirectToAction("Index");
            }
            return View(user);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var food = await _userService.GetItem(id);
            return View(food);
        }

        [HttpPost]
        [Obsolete]
        public async Task<IActionResult> Edit(User user)
        {
            user.DisplayName = user.FirstName + " " + user.LastName;
            var result = await _userService.Update(user);
            if (result)
            {
                return RedirectToAction("Index");
            }
            return View(user);
        }

        public async Task<IActionResult> Delete(string id)
        {
            await _userService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

CanteenASP/CanteenASP/Controllers/Components/UserInforViewComponent.cs
using API;
using Microsoft.AspNetCore.Mvc;

namespace CanteenASP.Controllers.Components
{
    public class UserInforViewComponent : ViewComponent
    {
        UserService _userService = new UserService(); 
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var userId = HttpContext.Session.GetString("UserId");
            
            if(userId == null)
            {
                Model.User user = null;
                return View("Default", user);
            }
            else
            {
                var user = await _userService.GetItem(userId);
                return View("Default", user);
            }
        }
    }
}

CanteenASP/CanteenASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Canteen</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link rel="stylesheet" href="~/css/all.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/styles-sb.css" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-primary">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" asp-area="" asp-controller="Home" asp-action="Index">

                    <img src="/logo.png" style="width: 50px;" alt="logo">
                    <label>Canteen</label>
        </a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item" style="padding-top: 10px; color: rgba(255, 255, 255, 0.55); margin-right: 20px">Xin chào @await Component.InvokeAsync("UserInfor")!</li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" asp-action="Infor" asp-controller="User">Personal information</a></li>
                    <li><a class="dropdown-item" asp-action="Reset" asp-controller="User">Reset password</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" asp-action="Logout" asp-controller="User">Logout</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-light" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Cart</div>
                        <a class="nav-link" asp-action="Index" asp-controller="Home" asp-route-meal=0>
                            <div class="sb-nav-link-icon"><i class="fas fa-box-open"></i></div>
                            Your order
                        </a>
                        <div class="sb-sidenav-menu-heading">Meal</div>
                        <a class="nav-link" asp-action="Meals" asp-controller="Home" asp-route-meal=1>
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Breakfast
                        </a>
                        <a class="nav-link" asp-action="Meals" asp-controller="Home" asp-route-meal=2>
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Lunch
                        </a>
                        <a class="nav-link" asp-action="Meals" asp-controller="Home" asp-route-meal=3>
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dinner
                        </a>
                    </div>
                </div>
               
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid pd-0">
                    @RenderBody()
                </div>
            </main>

        </div>
    </div>

    <script src="/js/jquery.min.js"></script>

    <script src="~/js/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="/js/script.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>